# Generated by Django 4.2.2 on 2023-06-29 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_reservas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_personas', models.IntegerField()),
                ('total_servicios', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_eventos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_alimentos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_general', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alimentos', models.ManyToManyField(to='tasks.alimentos')),
                ('eventos', models.ManyToManyField(to='tasks.eventos')),
                ('servicios', models.ManyToManyField(to='tasks.servicio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
