# Generated by Django 4.2.2 on 2023-06-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='titulo',
            field=models.CharField(default='Reserva', max_length=255),
        ),
    ]
