# Generated by Django 4.2.2 on 2023-06-30 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_reservas1_remove_reserva_alimentos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='reservas1',
            old_name='fecha',
            new_name='fecha_reserva',
        ),
        migrations.RemoveField(
            model_name='reservas1',
            name='total_alimentos',
        ),
        migrations.RemoveField(
            model_name='reservas1',
            name='total_eventos',
        ),
        migrations.RemoveField(
            model_name='reservas1',
            name='total_general',
        ),
        migrations.RemoveField(
            model_name='reservas1',
            name='total_servicios',
        ),
        migrations.AlterField(
            model_name='reservas1',
            name='cantidad_personas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservas1',
            name='titulo',
            field=models.CharField(max_length=1000),
        ),
    ]
