# Generated by Django 4.2.2 on 2023-06-30 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_reservas_rename_fecha_reservas1_fecha_reserva_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reservas',
        ),
        migrations.DeleteModel(
            name='Reservas1',
        ),
    ]
