# Generated by Django 4.2.2 on 2023-06-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_delete_reservas_delete_reservas1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('usuario', models.CharField(max_length=100)),
                ('servicios', models.CharField(max_length=100)),
                ('eventos', models.CharField(max_length=100)),
                ('alimentos', models.CharField(max_length=100)),
                ('cantidad_personas', models.DecimalField(decimal_places=0, max_digits=3)),
                ('fecha_reserva', models.DateField()),
            ],
        ),
    ]
